# Generated by Django 4.2.4 on 2023-09-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='emaillog',
            options={'verbose_name': 'Журнал', 'verbose_name_plural': 'Журналы электронной почты'},
        ),
        migrations.AlterModelOptions(
            name='marketingemail',
            options={'verbose_name': 'письмо', 'verbose_name_plural': 'Маркетинговые электронные письма'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
    ]
