# Generated by Django 4.2.4 on 2023-09-26 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0004_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='email_service.marketingemail'),
        ),
    ]
