# Generated by Django 4.2.4 on 2023-09-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0005_alter_message_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingemail',
            name='message',
            field=models.ManyToManyField(related_name='newsletters', to='email_service.message'),
        ),
        migrations.AlterField(
            model_name='marketingemail',
            name='clients',
            field=models.ManyToManyField(related_name='newsletters', to='email_service.client'),
        ),
        migrations.AlterField(
            model_name='marketingemail',
            name='frequency',
            field=models.CharField(max_length=200, verbose_name='частота отправки'),
        ),
        migrations.AlterField(
            model_name='marketingemail',
            name='status',
            field=models.CharField(max_length=200, verbose_name='состояние'),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='email_service.marketingemail'),
        ),
    ]
