# Generated by Django 4.2.4 on 2023-09-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0006_marketingemail_message_alter_marketingemail_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingemail',
            name='clients',
            field=models.ManyToManyField(related_name='newsletters', to='email_service.client', verbose_name='Кому'),
        ),
        migrations.AlterField(
            model_name='marketingemail',
            name='email_time',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='marketingemail',
            name='message',
            field=models.ManyToManyField(related_name='newsletters', to='email_service.message', verbose_name='Сообщение'),
        ),
    ]
